// Generated by scripts/gen-icons.py — do not edit by hand.
//
// Lucide v0.562.0, ISC licensed. https://lucide.dev
//
// `stroke` is a literal `black` rather than Lucide's `currentColor`:
// outside a browser there is no current colour, and every icon here is
// drawn as a template image, which takes its shape from the alpha
// channel and its colour from the caller.

enum LucideIcon: String, CaseIterable {
    case globe = "globe"

    /// The icon's SVG source.
    var svg: String {
        switch self {
        case .globe:
            return ##"<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/><path d="M2 12h20"/></svg>"##
        }
    }
}
