import Testing
import AppKit
import Foundation
import LanedCore
import RelayClient
@testable import MaxPaneKit

/// Paste history (ADR-0031): what is kept of each kind of paste and copy, what
/// never is, and the picker over it. Every pasteboard here is a private named
/// one; `NSPasteboard.general` is never read or written.

@Suite("paste history: a pasteboard marked secret says so as it is read")
@MainActor
struct PasteHistoryMarkerTests {
    private func board() -> NSPasteboard {
        let board = NSPasteboard(name: .init("maxpane.tests.paste-history.marker.\(UUID().uuidString)"))
        board.clearContents()
        return board
    }

    @Test("each of the three nspasteboard.org types", arguments: [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
    ])
    func marked(type: String) {
        let board = board()
        defer { board.releaseGlobally() }
        board.declareTypes([.string, .init(type)], owner: nil)
        board.setString("hunter2", forType: .string)
        board.setString("", forType: .init(type))
        let read = TerminalPaste.clipboard(board)
        #expect(read.text == "hunter2", "it still pastes")
        #expect(read.doNotRecord)
    }

    @Test("an ordinary copy is not marked, and neither is an empty pasteboard")
    func unmarked() {
        let board = board()
        defer { board.releaseGlobally() }
        #expect(!TerminalPaste.clipboard(board).doNotRecord)
        board.setString("ls -la", forType: .string)
        #expect(!TerminalPaste.clipboard(board).doNotRecord)
    }

    @Test("a marked pasteboard of files is marked too")
    func markedFiles() {
        let board = board()
        defer { board.releaseGlobally() }
        board.writeObjects([URL(fileURLWithPath: "/tmp/secret.key") as NSURL])
        board.addTypes([.init("org.nspasteboard.ConcealedType")], owner: nil)
        board.setString("", forType: .init("org.nspasteboard.ConcealedType"))
        let read = TerminalPaste.clipboard(board)
        #expect(read.text == "/tmp/secret.key")
        #expect(read.doNotRecord)
    }
}

@Suite("paste history: what the pane's one door records", .serialized)
@MainActor
struct PasteHistoryDoorTests {
    @MainActor
    final class Wire: RelayAttachment {
        let sessionId = "paste-history-test"
        var onData: ((ArraySlice<UInt8>) -> Void)?
        var onHostResize: ((Int, Int) -> Void)?
        var onTitle: ((String) -> Void)?
        var onExit: ((Int32) -> Void)?
        var onConnectionChange: ((Bool) -> Void)?
        var onRefused: ((String) -> Void)?
        var onReplaceScreen: (() -> Void)?
        var sent: [UInt8] = []
        func connect() {}
        func disconnect() {}
        func send(_ bytes: ArraySlice<UInt8>) { sent.append(contentsOf: bytes) }
        func send(_ bytes: ArraySlice<UInt8>, pace: PacedInput.Pace, report: @escaping (PacedInput.SlowEvent) -> Void) {
            sent.append(contentsOf: bytes)
            report(.finished(bytes.count))
        }
        func cancelSlowSend() {}
        func claimSize(cols: Int, rows: Int) {}
        var text: String { String(decoding: sent, as: UTF8.self) }
    }

    @MainActor
    final class Rig {
        let dir: URL
        let store: StripStore
        let window: NSWindow
        let pane: TerminalPaneController
        let wire = Wire()
        let pasteboard = NSPasteboard(name: .init("maxpane.tests.paste-history.\(UUID().uuidString)"))
        var config: Config

        /// `privateLane`: the terminal is a second pane of a private web lane.
        init(config: Config = Config(), privateLane: Bool = false) throws {
            self.config = config
            dir = FileManager.default.temporaryDirectory
                .appendingPathComponent("maxpane-paste-history-\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            store = try StripStore(ledgerPath: dir.appendingPathComponent("ledger.db").path)
            let terminal: Pane
            if privateLane {
                try store.newWebLane(url: "https://mail.example/", near: nil, private: true)
                let lane = try #require(store.state.lanes.first)
                try store.addPane(to: lane.id, kind: .pty, relaySessionId: "paste-history", url: nil)
                terminal = try #require(store.state.lanes[0].panes.first { $0.kind == .pty })
            } else {
                try store.newTerminalLane(relaySessionId: "paste-history", near: nil)
                terminal = store.state.lanes[0].panes[0]
            }
            window = NSWindow(
                contentRect: NSRect(x: -8000, y: 200, width: 700, height: 600),
                styleMask: [.borderless], backing: .buffered, defer: false)
            window.isReleasedWhenClosed = false
            pane = TerminalPaneController(
                pane: terminal, store: store, config: config,
                controller: TerminalControllerPool.makeController(for: config))
            pane.pasteboard = pasteboard
            pane.liveConfig = { [unowned self] in self.config }
            pane.attach(wire)
            pane.view.frame = NSRect(x: 0, y: 0, width: 656, height: 600)
            window.contentView?.addSubview(pane.view)
            pasteboard.clearContents()
        }

        func copy(_ text: String, marker: String? = nil) {
            pasteboard.clearContents()
            pasteboard.setString(text, forType: .string)
            if let marker {
                pasteboard.addTypes([.init(marker)], owner: nil)
                pasteboard.setString("", forType: .init(marker))
            }
        }

        func settle() async throws { try await Task.sleep(nanoseconds: 120_000_000) }

        var history: [ClipEntry] { store.clipHistory(config) }
        var kept: [String] { history.map(\.content) }

        func close() {
            pane.tearDown()
            pasteboard.releaseGlobally()
            window.close()
            try? FileManager.default.removeItem(at: dir)
        }
    }

    @Test("⌘V records what was sent: the tidied text, as a paste")
    func textPaste() throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.copy("$ git commit —amend\n")
        rig.pane.pasteFromClipboard()
        #expect(rig.kept == ["git commit --amend"])
        #expect(rig.history[0].kind == .paste)
        #expect(!rig.history[0].redacted)
    }

    @Test("⌥⌘V records it as it was copied")
    func withoutAsking() throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.copy("$ ls —all")
        rig.pane.pasteFromClipboard(asking: false)
        #expect(rig.kept == ["$ ls —all"])
    }

    @Test("a password manager's copy pastes and is never recorded", arguments: [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
    ])
    func concealed(marker: String) async throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.copy("hunter2", marker: marker)
        rig.pane.pasteFromClipboard()
        try await rig.settle()
        #expect(rig.wire.text == "hunter2")
        #expect(rig.kept.isEmpty)
        // Nor through a transform, nor slowly, nor unasked.
        rig.pane.pasteSpecial(.escaped)
        rig.pane.pasteSpecial(.base64)
        rig.pane.pasteSpecial(.slowly)
        rig.pane.pasteFromClipboard(asking: false)
        #expect(rig.kept.isEmpty)
    }

    @Test("a concealed paste that went through the sheet is not recorded either")
    func concealedThroughSheet() async throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.copy("one\ntwo", marker: "org.nspasteboard.ConcealedType")
        rig.pane.pasteFromClipboard()
        try #require(rig.pane.pasteSheet).answer(.paste(oneLine: false, tabsToSpaces: false))
        try await rig.settle()
        #expect(rig.wire.text == "one\rtwo")
        #expect(rig.kept.isEmpty)
    }

    @Test("a private lane records nothing, whatever the caller: paste, copy, a program's copy")
    func privateLane() async throws {
        let rig = try Rig(privateLane: true)
        defer { rig.close() }
        rig.copy("in a private lane")
        rig.pane.pasteFromClipboard()
        try await rig.settle()
        #expect(rig.wire.text == "in a private lane")
        rig.pane.selectionSource = { "selected in private" }
        rig.pane.selectionCopied()
        rig.pane.programSetClipboard("yanked in private")
        rig.pane.paste(fromHistory: "replayed in private")
        #expect(rig.kept.isEmpty)
    }

    @Test("a cancelled sheet records nothing; an answered one records what it sent")
    func sheet() throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.copy("echo one\necho two")
        rig.pane.pasteFromClipboard()
        try #require(rig.pane.pasteSheet).answer(.cancelled)
        #expect(rig.wire.sent.isEmpty)
        #expect(rig.kept.isEmpty)

        rig.pane.pasteFromClipboard()
        try #require(rig.pane.pasteSheet).answer(.paste(oneLine: true, tabsToSpaces: false))
        #expect(rig.kept == ["echo one echo two"])
    }

    @Test("copied files record their paths as pasted")
    func files() throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.pasteboard.clearContents()
        rig.pasteboard.writeObjects([
            URL(fileURLWithPath: "/tmp/a.txt") as NSURL, URL(fileURLWithPath: "/tmp/my file.txt") as NSURL,
        ])
        rig.pane.pasteFromClipboard()
        #expect(rig.kept == ["/tmp/a.txt \"/tmp/my file.txt\""])
    }

    @Test("a pasted picture records the path it became")
    func image() async throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.pane.pastedImages = PastedImages(directory: rig.dir.appendingPathComponent("paste"))
        let rep = try #require(NSBitmapImageRep(
            bitmapDataPlanes: nil, pixelsWide: 2, pixelsHigh: 2, bitsPerSample: 8, samplesPerPixel: 4,
            hasAlpha: true, isPlanar: false, colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0))
        rig.pasteboard.clearContents()
        rig.pasteboard.setData(try #require(rep.representation(using: .png, properties: [:])), forType: .png)
        rig.pane.pasteFromClipboard()
        let kept = try #require(rig.kept.first)
        #expect(kept.hasSuffix(".png") || kept.hasSuffix(".png\""))
        #expect(kept.contains("paste-"))
        try await rig.settle()
        #expect(rig.wire.text == kept)
    }

    @Test("Paste Special records the bytes it sent, not the clipboard")
    func transforms() throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.copy("two words")
        rig.pane.pasteSpecial(.escaped)
        rig.pane.pasteSpecial(.base64)
        #expect(rig.kept == ["dHdvIHdvcmRz", "\"two words\""])
        rig.copy("aGVsbG8=")
        rig.pane.pasteSpecial(.base64Decoded)
        #expect(rig.kept.first == "hello")
    }

    @Test("base64 of a secret is not kept in any form; escaped, it is redacted by the net")
    func transformedSecret() async throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.copy("sk-ant-api03-abcdefghijklmnopqrstuvwx")
        rig.pane.pasteSpecial(.base64)
        try await rig.settle()
        #expect(!rig.wire.sent.isEmpty)
        #expect(rig.kept.isEmpty)
        rig.pane.pasteSpecial(.escaped)
        #expect(rig.kept == ["sk-a•••"])
    }

    @Test("Paste File as Base64 is a file's contents and is never recorded")
    func heredoc() async throws {
        let rig = try Rig()
        defer { rig.close() }
        let file = rig.dir.appendingPathComponent("note.txt")
        try Data("hello".utf8).write(to: file)
        rig.pane.pasteAsBase64(files: [file])
        try await rig.settle()
        #expect(rig.wire.text.contains("base64 -d"))
        #expect(rig.kept.isEmpty)
    }

    @Test("Paste Slowly records the text it set going")
    func slowly() throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.copy("make flash")
        rig.pane.pasteSpecial(.slowly)
        #expect(rig.kept == ["make flash"])
    }

    @Test("a secret shape is kept as four characters and •••")
    func secretShape() async throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.copy("export GH=ghp_abcdefghijklmnopqrstuvwxyz0123456789")
        rig.pane.pasteFromClipboard()
        try await rig.settle()
        #expect(rig.wire.text.hasSuffix("0123456789"), "the paste itself is untouched")
        #expect(rig.kept == ["expo•••"])
        #expect(rig.history[0].redacted)
        #expect(clipSecretShape(text: "AKIAIOSFODNN7EXAMPLE") == "aws")
        #expect(clipSecretShape(text: "-----BEGIN RSA PRIVATE KEY-----") == "pem")
        #expect(clipSecretShape(text: "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHl0w5N") == "jwt")
        #expect(clipSecretShape(text: "ls -la") == nil)
    }

    @Test("more than 64 KB is not recorded, and 64 KB is")
    func tooBig() throws {
        var config = Config()
        config.pasteConfirmBytes = 0
        let rig = try Rig(config: config)
        defer { rig.close() }
        rig.copy(String(repeating: "a", count: 64 * 1024 + 1))
        rig.pane.pasteFromClipboard(asking: false)
        #expect(rig.kept.isEmpty)
        rig.copy(String(repeating: "a", count: 64 * 1024))
        rig.pane.pasteFromClipboard(asking: false)
        #expect(rig.history.count == 1)
    }

    @Test("copies out of a terminal: ⌘C, a program's OSC 52, and copy-on-select only when it is on")
    func copies() throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.pane.selectionSource = { "a1b2c3d" }
        rig.pane.selectionCopied()
        rig.pane.programSetClipboard("yanked in vim")
        #expect(rig.kept == ["yanked in vim", "a1b2c3d"])
        #expect(rig.history.allSatisfy { $0.kind == .copy })
        // `copy_on_select` is off: the end of a drag copies nothing, so
        // nothing is recorded.
        rig.pane.selectionSource = { "dragged" }
        rig.pane.selectionEnded()
        #expect(rig.kept.count == 2)

        var on = Config()
        on.copyOnSelect = true
        let second = try Rig(config: on)
        defer { second.close() }
        second.pane.selectionSource = { "dragged" }
        second.pane.selectionEnded()
        #expect(second.kept == ["dragged"])
    }

    @Test("a program's copy that was denied is not recorded")
    func deniedProgramCopy() throws {
        var config = Config()
        config.osc52Write = .deny
        let rig = try Rig(config: config)
        defer { rig.close() }
        rig.pane.programSetClipboard("nope")
        #expect(rig.kept.isEmpty)
    }

    @Test("paste_history = false records nothing and empties the table, read at each paste")
    func off() throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.copy("kept for now")
        rig.pane.pasteFromClipboard()
        #expect(rig.kept == ["kept for now"])
        rig.config.pasteHistory = false
        rig.store.applyPasteHistorySettings(rig.config)
        rig.pane.pasteFromClipboard()
        rig.config.pasteHistory = true
        #expect(rig.kept.isEmpty, "turning it back on does not bring anything back")

        rig.config.pasteHistoryKeep = 0
        rig.pane.pasteFromClipboard()
        rig.config.pasteHistoryKeep = 200
        #expect(rig.kept.isEmpty)
    }

    @Test("the cap keeps the newest, and the same text again moves to the top")
    func cap() throws {
        var config = Config()
        config.pasteHistoryKeep = 3
        let rig = try Rig(config: config)
        defer { rig.close() }
        for text in ["one", "two", "three", "four", "two"] {
            rig.copy(text)
            rig.pane.pasteFromClipboard()
        }
        #expect(rig.kept == ["two", "four", "three"])
    }

    @Test("an entry pasted from history goes untidied, asks when it is risky, and moves to the top")
    func replay() async throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.copy("first")
        rig.pane.pasteFromClipboard()
        rig.copy("second")
        rig.pane.pasteFromClipboard()
        rig.wire.sent = []

        // Curly quotes stay: it is what was kept, not a fresh copy.
        try await rig.settle()
        rig.wire.sent = []
        rig.pane.paste(fromHistory: "echo “first”")
        try await rig.settle()
        #expect(rig.wire.text == "echo “first”")
        #expect(rig.pane.noticeText == nil)
        rig.pane.paste(fromHistory: "first")
        #expect(rig.kept == ["first", "echo “first”", "second"])

        try await rig.settle()
        rig.wire.sent = []
        rig.pane.paste(fromHistory: "one\ntwo")
        #expect(rig.pane.pasteSheet != nil, "several lines ask first, from history too")
        #expect(rig.wire.sent.isEmpty)
        try #require(rig.pane.pasteSheet).answer(.cancelled)
        #expect(!rig.kept.contains("one\ntwo"))
    }

    @Test("Clear Paste History deletes every row")
    func clear() throws {
        let rig = try Rig()
        defer { rig.close() }
        for text in ["a", "b"] {
            rig.copy(text)
            rig.pane.pasteFromClipboard()
        }
        #expect(rig.store.clearClipHistory() == 2)
        #expect(rig.kept.isEmpty)
    }
}

@Suite("paste history: the picker")
@MainActor
struct PasteHistoryPickerTests {
    private func entry(
        _ id: Int64, _ content: String, kind: ClipKind = .paste, source: ClipSource = .pty,
        redacted: Bool = false, at: Int64 = 0
    ) -> ClipEntry {
        ClipEntry(
            id: id, kind: kind, source: source, content: content, redacted: redacted,
            lineCount: UInt32(content.split(separator: "\n").count), byteCount: UInt64(content.utf8.count), at: at)
    }

    @Test("nothing typed is everything, newest first as given; typing keeps the order and filters by substring")
    func ranking() {
        let all = [
            entry(3, "git push origin main"), entry(2, "/Users/you/code/max-pane/README.md"),
            entry(1, "git commit --amend\nGit is fine"),
        ]
        #expect(PasteHistory.filter(all, query: "").map(\.id) == [3, 2, 1])
        #expect(PasteHistory.filter(all, query: "  ").map(\.id) == [3, 2, 1])
        #expect(PasteHistory.filter(all, query: "GIT").map(\.id) == [3, 1], "case is ignored, newest stays first")
        #expect(PasteHistory.filter(all, query: "git amend").map(\.id) == [1], "every word must be there")
        #expect(PasteHistory.filter(all, query: "readme").map(\.id) == [2])
        #expect(PasteHistory.filter(all, query: "gti").isEmpty, "substring, not fuzzy")
    }

    @Test("a row is one line: the first with anything on it, or the one that matched")
    func headline() {
        let e = entry(1, "\n  cd /tmp\n\tmake all\n")
        #expect(PasteHistory.headline(e) == "cd /tmp")
        #expect(PasteHistory.headline(e, query: "make") == "make all")
        #expect(PasteHistory.headline(e, query: "nothing") == "cd /tmp")
        #expect(PasteHistory.headline(entry(2, "a\tb\u{1b}[0m")) == "a␉b␛[0m")
        #expect(PasteHistory.matches(in: "make all", query: "MA l") == [0, 1, 6, 7])
    }

    @Test("the detail line has which way, the line count, the size and the age")
    func detail() {
        let now = Date(timeIntervalSince1970: 10_000)
        let pasted = entry(1, "a\nb\nc", at: Int64((10_000 - 300) * 1000))
        #expect(PasteHistory.detail(pasted, now: now) == "pasted · 3 lines · 5 bytes · 5m ago")
        let copied = entry(2, "x", kind: .copy, at: Int64(10_000 * 1000))
        #expect(PasteHistory.detail(copied, now: now) == "copied · 1 line · 1 byte · now")
        let secret = entry(3, "expo•••", redacted: true, at: Int64(10_000 * 1000))
        #expect(PasteHistory.detail(secret, now: now).hasPrefix("looked like a secret, not kept · pasted"))
    }

    @Test("every row says which kind of pane it came from")
    func chip() {
        #expect(PasteHistory.chipText(entry(1, "ls")) == "PTY")
        #expect(PasteHistory.chipText(entry(2, "a token", kind: .copy, source: .web)) == "WEB")
        // The chip is on the row itself, not only in the model.
        let row = PasteHistoryRow(entry: entry(3, "a token", kind: .copy, source: .web), query: "")
        let words = row.subviews.flatMap { $0.subviews }.compactMap { ($0 as? NSTextField)?.stringValue }
        #expect(words.contains("WEB"))
    }

    @MainActor
    private final class Rig {
        let dir: URL
        let store: StripStore
        let paneId: String
        var config = Config()
        let pasteboard = NSPasteboard(name: .init("maxpane.tests.paste-history.picker.\(UUID().uuidString)"))
        var delivered: [ClipEntry?] = []

        init() throws {
            dir = FileManager.default.temporaryDirectory
                .appendingPathComponent("maxpane-paste-history-picker-\(UUID().uuidString)")
            try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
            store = try StripStore(ledgerPath: dir.appendingPathComponent("ledger.db").path)
            try store.newTerminalLane(relaySessionId: "picker", near: nil)
            paneId = store.state.lanes[0].panes[0].id
            pasteboard.clearContents()
        }

        func keep(_ text: String, _ kind: ClipKind = .paste, _ source: ClipSource = .pty) {
            store.recordClip(paneId: paneId, kind: kind, source: source, text: text, config: config)
        }

        func picker(canPaste: Bool = true) -> PasteHistoryController {
            let picker = PasteHistoryController(
                store: store, config: { [unowned self] in self.config }, canPaste: canPaste, pasteboard: pasteboard
            ) { [unowned self] in self.delivered.append($0) }
            picker.reload()
            return picker
        }

        func close() {
            pasteboard.releaseGlobally()
            try? FileManager.default.removeItem(at: dir)
        }
    }

    @Test("the list is the ledger's, newest first, and typing filters it")
    func lists() throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.keep("/tmp/a path")
        rig.keep("git status", .copy)
        let picker = rig.picker()
        #expect(picker.visible.map(\.content) == ["git status", "/tmp/a path"])
        #expect(picker.numberOfRows() == 2)
        #expect(picker.view(forRow: 0) is PasteHistoryRow)
        picker.setQuery("path")
        picker.reload()
        #expect(picker.visible.map(\.content) == ["/tmp/a path"])
        #expect(picker.footerLeft.stringValue == "1 OF 2")
    }

    @Test("↩ hands the entry to be pasted; a redacted row and a picker with no terminal hand over nothing")
    func pastePath() throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.keep("export KEY=sk-ant-api03-abcdefghijklmnopqrstuvwx")
        rig.keep("ls -la")
        let picker = rig.picker()
        picker.deliver(selected: 0)
        #expect(rig.delivered.last??.content == "ls -la")
        picker.deliver(selected: 1)
        #expect(rig.delivered.count == 2 && rig.delivered[1] == nil)
        #expect(picker.pasteRefusal(picker.visible[1]) != nil)
        picker.deliver(selected: -1)
        #expect(rig.delivered.count == 3 && rig.delivered[2] == nil)

        let noTerminal = rig.picker(canPaste: false)
        noTerminal.deliver(selected: 0)
        #expect(rig.delivered.count == 4 && rig.delivered[3] == nil)
        #expect(noTerminal.footerRight.stringValue.hasPrefix("⌘C"))
    }

    @Test("⌘C puts the row back on the clipboard it was given, and a redacted row has nothing to copy")
    func copies() throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.keep("ghp_abcdefghijklmnopqrstuvwxyz0123456789")
        rig.keep("one\ntwo\n")
        let picker = rig.picker()
        #expect(picker.copy(row: 0))
        #expect(rig.pasteboard.string(forType: .string) == "one\ntwo\n")
        #expect(!picker.copy(row: 1))
        #expect(rig.pasteboard.string(forType: .string) == "one\ntwo\n")
        #expect(!picker.copy(row: 7))
    }

    @Test("deleting a row removes it from the ledger and from the list")
    func deletes() throws {
        let rig = try Rig()
        defer { rig.close() }
        for text in ["a", "b", "c"] { rig.keep(text) }
        let picker = rig.picker()
        picker.delete(picker.visible[1])
        #expect(picker.visible.map(\.content) == ["c", "a"])
        #expect(rig.store.clipHistory(rig.config).map(\.content) == ["c", "a"])
        let prompt = PasteHistory.deletePrompt(picker.visible[0])
        #expect(prompt.title == "Delete this from paste history?")
        #expect(prompt.detail == "c")
    }

    @Test("with the setting off the list is empty and says why")
    func off() throws {
        let rig = try Rig()
        defer { rig.close() }
        rig.keep("soon gone")
        rig.config.pasteHistory = false
        let picker = rig.picker()
        #expect(picker.visible.isEmpty)
        #expect(picker.footerLeft.stringValue.contains("PASTE HISTORY IS OFF"))
    }
}

@Suite("paste history: the commands and the settings")
struct PasteHistoryCommandTests {
    @Test("⇧⌘H, in the Edit menu, beside a Clear with no key")
    func commands() {
        #expect(Command.pasteHistory.defaultShortcut?.0 == "h")
        #expect(Command.pasteHistory.defaultShortcut?.1 == [.command, .shift])
        #expect(Command.pasteHistory.menu == .edit)
        #expect(Command.pasteHistory.submenu == nil)
        #expect(Command.clearPasteHistory.defaultShortcut == nil)
        #expect(Command.clearPasteHistory.menu == .edit)
        let taken = Command.allCases.filter {
            $0 != .pasteHistory && $0.defaultShortcut?.0 == "h" && $0.defaultShortcut?.1 == [.command, .shift]
        }
        #expect(taken.isEmpty)
    }

    @Test("the three settings, on by default, applied live")
    func settings() throws {
        let config = Config()
        #expect(config.pasteHistory)
        #expect(config.pasteHistoryKeep == 200)
        #expect(config.pasteHistoryDays == 30)
        for name in ["pasteHistory", "pasteHistoryKeep", "pasteHistoryDays"] {
            let field = try #require(ConfigField.all.first { $0.name == name })
            #expect(field.appliesLive)
            #expect(field.group == .terminals)
        }
    }
}
