// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_CLONE_CORE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_CLONE_CORE
uint64_t uniffi_laned_core_fn_clone_core(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_FREE_CORE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_FREE_CORE
void uniffi_laned_core_fn_free_core(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_CONSTRUCTOR_CORE_OPEN
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_CONSTRUCTOR_CORE_OPEN
uint64_t uniffi_laned_core_fn_constructor_core_open(RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_CONSTRUCTOR_CORE_OPEN_IN_MEMORY
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_CONSTRUCTOR_CORE_OPEN_IN_MEMORY
uint64_t uniffi_laned_core_fn_constructor_core_open_in_memory(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_ADD_PANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_ADD_PANE
RustBuffer uniffi_laned_core_fn_method_core_add_pane(uint64_t ptr, RustBuffer lane_id, RustBuffer kind, RustBuffer relay_session_id, RustBuffer url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_CLOSE_LANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_CLOSE_LANE
RustBuffer uniffi_laned_core_fn_method_core_close_lane(uint64_t ptr, RustBuffer lane_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_CLOSE_PANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_CLOSE_PANE
RustBuffer uniffi_laned_core_fn_method_core_close_pane(uint64_t ptr, RustBuffer pane_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_CREATE_LANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_CREATE_LANE
RustBuffer uniffi_laned_core_fn_method_core_create_lane(uint64_t ptr, RustBuffer placement, RustBuffer kind, RustBuffer relay_session_id, RustBuffer url, RustBuffer inherit_tag_from_lane, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_FOCUS_PANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_FOCUS_PANE
RustBuffer uniffi_laned_core_fn_method_core_focus_pane(uint64_t ptr, RustBuffer pane_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_GATHER
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_GATHER
RustBuffer uniffi_laned_core_fn_method_core_gather(uint64_t ptr, RustBuffer project_root, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_LANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_LANE
RustBuffer uniffi_laned_core_fn_method_core_lane(uint64_t ptr, RustBuffer lane_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_MARK_EVICTED
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_MARK_EVICTED
RustBuffer uniffi_laned_core_fn_method_core_mark_evicted(uint64_t ptr, RustBuffer pane_id, RustBuffer snapshot_path, RustBuffer scroll_y, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_MARK_LIVE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_MARK_LIVE
RustBuffer uniffi_laned_core_fn_method_core_mark_live(uint64_t ptr, RustBuffer pane_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_MOVE_LANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_MOVE_LANE
RustBuffer uniffi_laned_core_fn_method_core_move_lane(uint64_t ptr, RustBuffer lane_id, RustBuffer placement, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_NOTE_FOCUS
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_NOTE_FOCUS
void uniffi_laned_core_fn_method_core_note_focus(uint64_t ptr, RustBuffer pane_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_NUDGE_LANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_NUDGE_LANE
RustBuffer uniffi_laned_core_fn_method_core_nudge_lane(uint64_t ptr, RustBuffer lane_id, int8_t right, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_OBSERVE_CWD
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_OBSERVE_CWD
int8_t uniffi_laned_core_fn_method_core_observe_cwd(uint64_t ptr, RustBuffer lane_id, RustBuffer cwd, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_PAIR
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_PAIR
void uniffi_laned_core_fn_method_core_pair(uint64_t ptr, RustBuffer pty_pane_id, RustBuffer web_pane_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_PAIRS_OF
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_PAIRS_OF
RustBuffer uniffi_laned_core_fn_method_core_pairs_of(uint64_t ptr, RustBuffer pane_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_PLAN_EVICTION
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_PLAN_EVICTION
RustBuffer uniffi_laned_core_fn_method_core_plan_eviction(uint64_t ptr, RustBuffer viewport, RustBuffer memory, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_PROJECT_ROOT_OF
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_PROJECT_ROOT_OF
RustBuffer uniffi_laned_core_fn_method_core_project_root_of(uint64_t ptr, RustBuffer cwd, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_PUSH_SCROLLBACK
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_PUSH_SCROLLBACK
void uniffi_laned_core_fn_method_core_push_scrollback(uint64_t ptr, RustBuffer pane_id, RustBuffer lines, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_REVISION
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_REVISION
uint64_t uniffi_laned_core_fn_method_core_revision(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SEARCH
RustBuffer uniffi_laned_core_fn_method_core_search(uint64_t ptr, RustBuffer query, uint32_t limit, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_LANE_TITLE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_LANE_TITLE
RustBuffer uniffi_laned_core_fn_method_core_set_lane_title(uint64_t ptr, RustBuffer lane_id, RustBuffer title, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_LANE_WIDTH
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_LANE_WIDTH
RustBuffer uniffi_laned_core_fn_method_core_set_lane_width(uint64_t ptr, RustBuffer lane_id, uint32_t width_pt, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_MANUAL_TAG
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_MANUAL_TAG
RustBuffer uniffi_laned_core_fn_method_core_set_manual_tag(uint64_t ptr, RustBuffer lane_id, RustBuffer project_root, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_PANE_DATA_STORE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_PANE_DATA_STORE
void uniffi_laned_core_fn_method_core_set_pane_data_store(uint64_t ptr, RustBuffer pane_id, RustBuffer data_store_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_PANE_SCROLL
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_PANE_SCROLL
void uniffi_laned_core_fn_method_core_set_pane_scroll(uint64_t ptr, RustBuffer pane_id, double scroll_y, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_PANE_URL
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_PANE_URL
void uniffi_laned_core_fn_method_core_set_pane_url(uint64_t ptr, RustBuffer pane_id, RustBuffer url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_PINNED
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_PINNED
RustBuffer uniffi_laned_core_fn_method_core_set_pinned(uint64_t ptr, RustBuffer lane_id, int8_t pinned, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_SCROLL_X
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_SET_SCROLL_X
void uniffi_laned_core_fn_method_core_set_scroll_x(uint64_t ptr, double scroll_x, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_STATE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_STATE
RustBuffer uniffi_laned_core_fn_method_core_state(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_UNGATHER
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_UNGATHER
RustBuffer uniffi_laned_core_fn_method_core_ungather(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_UNPAIR
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_FN_METHOD_CORE_UNPAIR
void uniffi_laned_core_fn_method_core_unpair(uint64_t ptr, RustBuffer pty_pane_id, RustBuffer web_pane_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUSTBUFFER_ALLOC
RustBuffer ffi_laned_core_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_laned_core_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUSTBUFFER_FREE
void ffi_laned_core_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUSTBUFFER_RESERVE
RustBuffer ffi_laned_core_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_U8
void ffi_laned_core_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_U8
void ffi_laned_core_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_U8
void ffi_laned_core_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_laned_core_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_I8
void ffi_laned_core_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_I8
void ffi_laned_core_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_I8
void ffi_laned_core_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_laned_core_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_U16
void ffi_laned_core_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_U16
void ffi_laned_core_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_U16
void ffi_laned_core_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_laned_core_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_I16
void ffi_laned_core_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_I16
void ffi_laned_core_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_I16
void ffi_laned_core_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_laned_core_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_U32
void ffi_laned_core_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_U32
void ffi_laned_core_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_U32
void ffi_laned_core_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_laned_core_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_I32
void ffi_laned_core_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_I32
void ffi_laned_core_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_I32
void ffi_laned_core_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_laned_core_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_U64
void ffi_laned_core_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_U64
void ffi_laned_core_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_U64
void ffi_laned_core_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_laned_core_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_I64
void ffi_laned_core_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_I64
void ffi_laned_core_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_I64
void ffi_laned_core_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_laned_core_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_F32
void ffi_laned_core_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_F32
void ffi_laned_core_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_F32
void ffi_laned_core_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_F32
float ffi_laned_core_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_F64
void ffi_laned_core_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_F64
void ffi_laned_core_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_F64
void ffi_laned_core_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_F64
double ffi_laned_core_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_laned_core_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_laned_core_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_laned_core_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_laned_core_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_POLL_VOID
void ffi_laned_core_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_CANCEL_VOID
void ffi_laned_core_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_FREE_VOID
void ffi_laned_core_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_LANED_CORE_RUST_FUTURE_COMPLETE_VOID
void ffi_laned_core_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_ADD_PANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_ADD_PANE
uint16_t uniffi_laned_core_checksum_method_core_add_pane(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_CLOSE_LANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_CLOSE_LANE
uint16_t uniffi_laned_core_checksum_method_core_close_lane(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_CLOSE_PANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_CLOSE_PANE
uint16_t uniffi_laned_core_checksum_method_core_close_pane(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_CREATE_LANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_CREATE_LANE
uint16_t uniffi_laned_core_checksum_method_core_create_lane(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_FOCUS_PANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_FOCUS_PANE
uint16_t uniffi_laned_core_checksum_method_core_focus_pane(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_GATHER
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_GATHER
uint16_t uniffi_laned_core_checksum_method_core_gather(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_LANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_LANE
uint16_t uniffi_laned_core_checksum_method_core_lane(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_MARK_EVICTED
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_MARK_EVICTED
uint16_t uniffi_laned_core_checksum_method_core_mark_evicted(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_MARK_LIVE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_MARK_LIVE
uint16_t uniffi_laned_core_checksum_method_core_mark_live(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_MOVE_LANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_MOVE_LANE
uint16_t uniffi_laned_core_checksum_method_core_move_lane(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_NOTE_FOCUS
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_NOTE_FOCUS
uint16_t uniffi_laned_core_checksum_method_core_note_focus(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_NUDGE_LANE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_NUDGE_LANE
uint16_t uniffi_laned_core_checksum_method_core_nudge_lane(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_OBSERVE_CWD
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_OBSERVE_CWD
uint16_t uniffi_laned_core_checksum_method_core_observe_cwd(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_PAIR
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_PAIR
uint16_t uniffi_laned_core_checksum_method_core_pair(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_PAIRS_OF
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_PAIRS_OF
uint16_t uniffi_laned_core_checksum_method_core_pairs_of(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_PLAN_EVICTION
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_PLAN_EVICTION
uint16_t uniffi_laned_core_checksum_method_core_plan_eviction(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_PROJECT_ROOT_OF
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_PROJECT_ROOT_OF
uint16_t uniffi_laned_core_checksum_method_core_project_root_of(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_PUSH_SCROLLBACK
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_PUSH_SCROLLBACK
uint16_t uniffi_laned_core_checksum_method_core_push_scrollback(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_REVISION
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_REVISION
uint16_t uniffi_laned_core_checksum_method_core_revision(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SEARCH
uint16_t uniffi_laned_core_checksum_method_core_search(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_LANE_TITLE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_LANE_TITLE
uint16_t uniffi_laned_core_checksum_method_core_set_lane_title(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_LANE_WIDTH
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_LANE_WIDTH
uint16_t uniffi_laned_core_checksum_method_core_set_lane_width(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_MANUAL_TAG
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_MANUAL_TAG
uint16_t uniffi_laned_core_checksum_method_core_set_manual_tag(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_PANE_DATA_STORE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_PANE_DATA_STORE
uint16_t uniffi_laned_core_checksum_method_core_set_pane_data_store(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_PANE_SCROLL
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_PANE_SCROLL
uint16_t uniffi_laned_core_checksum_method_core_set_pane_scroll(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_PANE_URL
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_PANE_URL
uint16_t uniffi_laned_core_checksum_method_core_set_pane_url(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_PINNED
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_PINNED
uint16_t uniffi_laned_core_checksum_method_core_set_pinned(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_SCROLL_X
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_SET_SCROLL_X
uint16_t uniffi_laned_core_checksum_method_core_set_scroll_x(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_STATE
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_STATE
uint16_t uniffi_laned_core_checksum_method_core_state(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_UNGATHER
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_UNGATHER
uint16_t uniffi_laned_core_checksum_method_core_ungather(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_UNPAIR
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_METHOD_CORE_UNPAIR
uint16_t uniffi_laned_core_checksum_method_core_unpair(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_CONSTRUCTOR_CORE_OPEN
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_CONSTRUCTOR_CORE_OPEN
uint16_t uniffi_laned_core_checksum_constructor_core_open(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_CONSTRUCTOR_CORE_OPEN_IN_MEMORY
#define UNIFFI_FFIDEF_UNIFFI_LANED_CORE_CHECKSUM_CONSTRUCTOR_CORE_OPEN_IN_MEMORY
uint16_t uniffi_laned_core_checksum_constructor_core_open_in_memory(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LANED_CORE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_LANED_CORE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_laned_core_uniffi_contract_version(void
    
);
#endif

