#!/usr/bin/env python3
"""Generate Sources/MaxPaneKit/Views/LucideIcons.swift from Lucide's sources.

Lucide ships its icons as ES modules holding an array of (tag, attrs) pairs,
not as SVG files, so this turns the ones we use into SVG and embeds them as
Swift string literals.

Embedded rather than shipped as a SwiftPM resource bundle on purpose: this app
is assembled by hand with no Xcode, `Bundle.module` would need the bundle
copied into Contents/Resources by build-app.sh, and the failure mode of getting
that wrong is icons that are silently absent. A string in the binary cannot go
missing.

    ./scripts/gen-icons.py [path-to-lucide-package]

The output is committed. Nothing in the build depends on Lucide being installed.
"""
import os, re, sys

DEFAULT_LUCIDE = os.path.expanduser("~/code/editor/node_modules/lucide")
OUT = "swift/MaxPane/Sources/MaxPaneKit/Views/LucideIcons.swift"

# The icons the app uses. Add here, re-run, commit the result.
WANTED = [
    # sidebar rows and controls
    "globe", "square-terminal", "plus", "chevron-down", "chevron-right",
    "arrow-up", "arrow-down", "panel-left", "panel-left-close",
    "list-filter", "chevrons-down-up", "chevrons-up-down",
    # web chrome
    "arrow-left", "arrow-right", "rotate-cw", "star", "search", "download",
    "x", "chevron-up",
    # lane header
    "ellipsis", "pin",
    # web chrome, continued
    "key-round", "check",
]

# Lucide draws everything as an outline. A filled variant is emitted for the
# icons whose *state* is the whole point — a kept bookmark against an unkept
# one — because two colours of the same outline is not a difference you can see
# across a row of controls.
FILLED = ["star"]

PAIR = re.compile(r'\[\s*"([A-Za-z][\w-]*)"\s*,\s*\{([^}]*)\}\s*\]')
ATTR = re.compile(r'([A-Za-z][\w-]*)\s*:\s*"([^"]*)"')


def svg_for(root: str, name: str) -> str:
    path = os.path.join(root, "dist/esm/icons", name + ".js")
    with open(path) as fh:
        source = fh.read()
    body = []
    for tag, attrs in PAIR.findall(source):
        rendered = " ".join(f'{k}="{v}"' for k, v in ATTR.findall(attrs))
        body.append(f"<{tag} {rendered}/>")
    if not body:
        raise SystemExit(f"no shapes parsed out of {path}")
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" '
        'viewBox="0 0 24 24" fill="none" stroke="black" stroke-width="2" '
        'stroke-linecap="round" stroke-linejoin="round">' + "".join(body) + "</svg>"
    )


def swift_case(name: str) -> str:
    head, *rest = name.split("-")
    return head + "".join(w.capitalize() for w in rest)


def main() -> None:
    root = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_LUCIDE
    if not os.path.isdir(root):
        raise SystemExit(f"no lucide package at {root}")
    version = "unknown"
    with open(os.path.join(root, "package.json")) as fh:
        m = re.search(r'"version":\s*"([^"]+)"', fh.read())
        if m:
            version = m.group(1)

    lines = [
        "// Generated by scripts/gen-icons.py — do not edit by hand.",
        "//",
        f"// Lucide v{version}, ISC licensed. https://lucide.dev",
        "//",
        "// `stroke` is a literal `black` rather than Lucide's `currentColor`:",
        "// outside a browser there is no current colour, and every icon here is",
        "// drawn as a template image, which takes its shape from the alpha",
        "// channel and its colour from the caller.",
        "",
        "enum LucideIcon: String, CaseIterable {",
    ]
    for name in WANTED:
        lines.append(f'    case {swift_case(name)} = "{name}"')
    for name in FILLED:
        lines.append(f'    case {swift_case(name)}Filled = "{name}-filled"')
    lines += ["", "    /// The icon's SVG source.", "    var svg: String {", "        switch self {"]
    for name in WANTED:
        lines.append(f"        case .{swift_case(name)}:")
        lines.append(f'            return ##"{svg_for(root, name)}"##')
    for name in FILLED:
        filled = svg_for(root, name).replace('fill="none"', 'fill="black"')
        lines.append(f"        case .{swift_case(name)}Filled:")
        lines.append(f'            return ##"{filled}"##')
    lines += ["        }", "    }", "}", ""]

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {OUT} ({len(WANTED)} icons from lucide {version})")


if __name__ == "__main__":
    main()
